# Generated by Django 2.2.dev20180523150237 on 2018-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='abc0070022@gmail.com', max_length=40, unique=True),
        ),
    ]
