# Generated by Django 2.2.dev20180523150237 on 2018-08-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images'),
        ),
    ]
