# Generated by Django 2.2.dev20180523150237 on 2018-08-18 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
