# Generated by Django 2.2.dev20180523150237 on 2018-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_customuser_jwt_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='avatar',
        ),
    ]
