# Generated by Django 2.2.dev20180523150237 on 2018-09-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180818_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jwt_secret',
        ),
    ]
