# Generated by Django 2.2.dev20180523150237 on 2018-08-04 16:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128)),
                ('nickname', models.CharField(default='nickname', max_length=40)),
                ('password', models.CharField(default='Nickname', max_length=16)),
                ('otp', models.CharField(editable=False, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'OTP Tokens',
                'verbose_name': 'OTP Token',
            },
        ),
    ]
