# Generated by Django 2.2.dev20180523150237 on 2018-08-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetoken',
            name='nickname',
        ),
    ]
