# Generated by Django 2.2.dev20180523150237 on 2018-08-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0002_remove_phonetoken_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetoken',
            name='phone_number',
        ),
    ]
