# Generated by Django 2.2.dev20180523150237 on 2018-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0004_auto_20180809_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='otp',
            field=models.CharField(max_length=40),
        ),
    ]
